### ISSUE TITLE
services no start help me.

### ISSUE THREAD

**Issue by zonhanoz09** [traccar/traccar#3322]
![image](https://user-images.githubusercontent.com/20008948/27915314-234c5974-6290-11e7-85a8-2432d3dd4cdf.png)

**Comment by zonhanoz09** [comment]
tôi đã cố gắng bật services. nhưng nó sẽ tắt vài giây sau đó

**Comment by zonhanoz09** [comment]
I tried to enable service. But it will turn off a few seconds later

**Comment by zonhanoz09** [comment]
![image](https://user-images.githubusercontent.com/20008948/27915531-e2b84f0c-6290-11e7-94b6-f401cbd2f2ff.png)

I changed the conf file to change to sql server database

**Comment by tananaev** [comment]
You should check wrapper log file for errors.

**Comment by zonhanoz09** [comment]
![image](https://user-images.githubusercontent.com/20008948/27941874-309ab900-62fd-11e7-9abc-5bb1784d6573.png)
I saw the log but did not know where the error was

**Comment by tananaev** [comment]
You should probably read my comment more carefully.

**Comment by zonhanoz09** [comment]
![image](https://user-images.githubusercontent.com/20008948/27942362-787f212c-6300-11e7-96c1-a429adecd4f6.png)

sorry. I guess I think it's in this place.

**Comment by tananaev** [comment]
I guess now you can see the error. Connection to your database has failed.

**Comment by zonhanoz09** [comment]
I have seen the error and am trying to fix it

**Comment by Copois** [comment]
I have same problem but my error isn't sql error

```
WARNING|wrapper|Service traccar|17-07-07 10:16:39|YAJSW: yajsw-stable-12.08
WARNING|wrapper|Service traccar|17-07-07 10:16:39|OS   : Windows 7/6.1/x86
WARNING|wrapper|Service traccar|17-07-07 10:16:39|JVM  : Oracle Corporation/1.8.0_121/C:\Program Files (x86)\Java\jre1.8.0_121/32
INFO|wrapper|Service traccar|17-07-07 10:16:39|start delay: 0
INFO|wrapper|Service traccar|17-07-07 10:16:40|started process with pid 8512
INFO|8512/0|Service traccar|17-07-07 10:16:41|[INFO] StandardFileSystemManager - Using "C:\windows\TEMP\vfs_cache" as temporary files store.
INFO|8512/0|Service traccar|17-07-07 10:16:42|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
INFO|8512/0|Service traccar|17-07-07 10:16:43|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
INFO|8512/0|Service traccar|17-07-07 10:16:43|INFO 7/7/17 10:16 AM: liquibase: Clearing database change log checksums
INFO|8512/0|Service traccar|17-07-07 10:16:43|INFO 7/7/17 10:16 AM: liquibase: Successfully acquired change log lock
INFO|8512/0|Service traccar|17-07-07 10:16:43|INFO 7/7/17 10:16 AM: liquibase: Successfully released change log lock
INFO|8512/0|Service traccar|17-07-07 10:16:43|INFO 7/7/17 10:16 AM: liquibase: Successfully acquired change log lock
INFO|8512/0|Service traccar|17-07-07 10:16:44|INFO 7/7/17 10:16 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO|8512/0|Service traccar|17-07-07 10:16:44|INFO 7/7/17 10:16 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO|8512/0|Service traccar|17-07-07 10:16:44|INFO 7/7/17 10:16 AM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::author: Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  Error: Constraint "UK_USER_TOKEN" not found; SQL statement:
INFO|8512/0|Service traccar|17-07-07 10:16:44|ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token [90057-194] [Failed SQL: ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token]
INFO|8512/0|Service traccar|17-07-07 10:16:44|INFO 7/7/17 10:16 AM: liquibase: Successfully released change log lock
INFO|8512/0|Service traccar|17-07-07 10:16:44|[main] INFO org.eclipse.jetty.util.log - Logging initialized @4294ms
INFO|8512/0|Service traccar|17-07-07 10:16:45|java.lang.reflect.InvocationTargetException
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at java.lang.reflect.Method.invoke(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|8512/0|Service traccar|17-07-07 10:16:45|Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:5037
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.traccar.TrackerServer.start(TrackerServer.java:117)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.traccar.ServerManager.start(ServerManager.java:81)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.traccar.Main.main(Main.java:38)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	... 6 more
INFO|8512/0|Service traccar|17-07-07 10:16:45|Caused by: java.net.BindException: Address already in use: bind
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at sun.nio.ch.Net.bind0(Native Method)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at sun.nio.ch.Net.bind(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at sun.nio.ch.Net.bind(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO|8512/0|Service traccar|17-07-07 10:16:45|	at java.lang.Thread.run(Unknown Source)
INFO|wrapper|Service traccar|17-07-07 10:16:45|calling onStop
INFO|wrapper|Service traccar|17-07-07 10:16:45|Win service stop - timeout: 30000
INFO|wrapper|Service traccar|17-07-07 10:16:45|Win service wrapper.control -> stopping application
INFO|wrapper|Service traccar|17-07-07 10:16:45|Win service stop - after shutdown
INFO|wrapper|Service traccar|17-07-07 10:16:45|Win service stop - before notify
INFO|wrapper|Service traccar|17-07-07 10:16:45|Win service terminated
```

**Comment by tananaev** [comment]
@Copois, your problem is completely different. You have a port conflict with some other process on your server.

**Comment by Copois** [comment]
I am sorry, i have change port and it's ok

**Comment by andi968** [comment]
I have the same problem with service stopping after a few seconds,How do I change localhost address to unused one
[wrapper.log.txt](https://github.com/tananaev/traccar/files/1130843/wrapper.log.txt)

**Comment by tananaev** [comment]
Change localhost address? That doesn't make any sense.

**Comment by andi968** [comment]
ok if that doesnt make sense < how do I cure the issue

**Comment by tananaev** [comment]
You need to change the conflicting port, or stop the other process that uses that port.

**Comment by andi968** [comment]
How do I  find what else is using the port? _ cant find anything in task manager
_

**Comment by tananaev** [comment]
You can try [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx).

**Comment by andi968** [comment]
I have installed and run that now, how do I track down the culprit

**Comment by tananaev** [comment]
I guess you have to look through the processes and find the ones that use ports 5xxx or 8082.

**Comment by andi968** [comment]
Nothing is apparent, I will try further on a vmware with nothing installed

**Comment by andi968** [comment]
On a VM service runs fine, however web portal opens blank page with "Powered By" in bottom right corner, no log in or anything else ?

**Comment by tananaev** [comment]
I would recommend to create a separate thread to discuss your issue because it has nothing to do with this thread. Also, you should check browser console for any errors and warnings.

**Comment by zonhanoz09** [comment]
I was edited to. Failed port for a service

**Comment by andi968** [comment]
My error is exactly the same ! I only used VM as a bench test, the fact of the matter is my problem is services stop after a few seconds, perhaps a list requires compiling of apps that use the port required ie 8082, or the ability to change ports, all background processes running are required for day to day tasks.

**Comment by tananaev** [comment]
Any port in Traccar can be changed.

**Comment by andi968** [comment]
Obviously I am not aware of this feature, I would appreciate some advice how to go about changing the port and avoiding conflicts and how to avoid the services stopping.

**Comment by tananaev** [comment]
Please read documentation on the official website.

**Comment by andi968** [comment]
Hi

I have now changed the port to http 80 and hey presto the service continues to run and I can get to the web interface.

I plan to use a Chinese no name TK110 along side my dyn account, do you foresee any further issues now I have changed ports ? I assume I set a rule up for port forwarding to forward incoming connections to port 80, is this correct?

 

Yours Faithfully

 

signature

          Andrew G M Stancliffe

 

 

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited

**Comment by tananaev** [comment]
Port 80 is definitely NOT for devices. Check this page:

https://www.traccar.org/devices/

**Comment by andi968** [comment]
after reading the manual that came with the unit, the only mention of ports is 10202 again this only runs for a few seconds and stops as do all the 5*** ports in documents.
The only port that works is 80 ! any suggestions to get the software to function ?

**Comment by tananaev** [comment]
It means that server is still not working... and the problem is likely the same as before. Have you checked logs?  If the error is the same, you should find conflicting port!

**Comment by andi968** [comment]
After digging an old laptop out and doing a clean install of windows 7 I can now log into the UI add a device (iPad using app) 
However as can be seen from attached pictures, I can still not connect to the server I also include the log

2017-07-08 09:37:03  INFO: Operating system name: Windows 7 version: 6.1 architecture: x86
2017-07-08 09:37:03  INFO: Java runtime name: Java HotSpot(TM) Client VM vendor: Oracle Corporation version: 25.131-b11
2017-07-08 09:37:03  INFO: Memory limit heap: 245mb non-heap: 0mb
2017-07-08 09:37:03  INFO: Character encoding: UTF-8 charset: UTF-8
2017-07-08 09:37:03  INFO: Version: 3.11-SNAPSHOT
2017-07-08 09:37:42  INFO: Starting server...
2017-07-08 09:48:33  INFO: [2720B92E] connected
2017-07-08 09:48:33  INFO: [72BD28D7] connected
2017-07-08 09:48:33 DEBUG: [2720B92E: 5001 < 0:0:0:0:0:0:0:1] HEX: 474554202f20485454502f312e310d0a486f73743a206c6f63616c686f73743a353030310d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a557067726164652d496e7365637572652d52657175657374733a20310d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e5420362e3129204170706c655765624b69742f3533372e333620284b48544d4c2c206c696b65204765636b6f29204368726f6d652f35392e302e333037312e313135205361666172692f3533372e33360d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c696d6167652f776562702c696d6167652f61706e672c2a2f2a3b713d302e380d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c2062720d0a4163636570742d4c616e67756167653a20656e2d47422c656e2d55533b713d302e382c656e3b713d302e360d0a436f6f6b69653a20757365723d595752746157342533443b2070617373776f72643d595752746157342533443b206578742d73686f772d67656f66656e6365732d627574746f6e3d6f25334170726573736564253344622532353341313b206578742d73686f772d6c6976652d726f757465732d627574746f6e3d6f25334170726573736564253344622532353341303b206578742d6465766963652d666f6c6c6f772d627574746f6e3d6f25334170726573736564253344622532353341303b206578742d736f756e642d627574746f6e3d6f25334170726573736564253344622532353341303b206578742d646576696365732d677269643d6f253341636f6c756d6e732533446125323533416f2532353235334169642532353235334473253235323532353341683125323535456f2532353235334169642532353235334473253235323532353341683225323535456f2532353235334169642532353235334473253235323532353341683325323535456f2532353235334169642532353235334473253235323532353341683425323535456f2532353235334169642532353235334473253235323532353341683525323535456f2532353235334169642532353235334473253235323532353341683625323535456f2532353235334169642532353235334473253235323532353341683725323535456f253235323533416964253235323533447325323532353235334168382535457765696768742533446e2532353341303b206578742d73746174652d677269643d6f253341636f6c756d6e732533446125323533416f2532353235334169642532353235334473253235323532353341683125323535456f2532353235334169642532
2017-07-08 09:48:33 DEBUG: [2720B92E: 5001 < 0:0:0:0:0:0:0:1] HEX: 353235334473253235323532353341683225354573746f726553746174652533446f2532353341736f7274657273253235334461253235323533416f253235323532353341726f6f742532353235323533447325323532353235323533416461746125323532353235354570726f70657274792532353235323533447325323532353235323533417072696f72697479253235323532353545646972656374696f6e25323532353235334473253235323532353235334141534325323532353235354569642532353235323533447325323532353235323533417072696f726974792535457765696768742533446e253235334131303b206578742d646576696365732d616e642d73746174652d70616e656c3d6f2533417765696768742533446e25323533412d31300d0a0d0a
2017-07-08 09:48:34  INFO: [72BD28D7] disconnected
2017-07-08 09:57:09  INFO: [2720B92E] disconnected
2017-07-08 11:09:01  INFO: Shutting down server...
2017-07-08 11:10:20  INFO: Operating system name: Windows 7 version: 6.1 architecture: x86
2017-07-08 11:10:20  INFO: Java runtime name: Java HotSpot(TM) Client VM vendor: Oracle Corporation version: 25.131-b11
2017-07-08 11:10:20  INFO: Memory limit heap: 245mb non-heap: 0mb
2017-07-08 11:10:20  INFO: Character encoding: UTF-8 charset: UTF-8
2017-07-08 11:10:20  INFO: Version: 3.11-SNAPSHOT
2017-07-08 11:10:40  INFO: Starting server...

![img_1219](https://user-images.githubusercontent.com/26763568/27984444-07d0eed2-63ce-11e7-914a-eb15368899be.PNG)
![img_1220](https://user-images.githubusercontent.com/26763568/27984446-07f09f52-63ce-11e7-8817-0366643af132.PNG)
![img_1221](https://user-images.githubusercontent.com/26763568/27984447-07f11c8e-63ce-11e7-99d2-afd7a233ae07.JPG)

**Comment by tananaev** [comment]
I have just checked and the port is closed.

Also, what you are using as a server address on iPad is completely wrong. You should be using something like this:

`http://92.31.105.92:8082/`

**Comment by andi968** [comment]
Try it again, laptop was updating and restarted

**Comment by tananaev** [comment]
It's working now. Should be working with Traccar Manager as well.

**Comment by andi968** [comment]
Success partial, Traccar client iOS says it is updating but servers say it is offline.
![img_1222](https://user-images.githubusercontent.com/26763568/27984646-37232524-63d3-11e7-8358-b0b7c3ff6eae.PNG)
![img_1223](https://user-images.githubusercontent.com/26763568/27984647-373e8918-63d3-11e7-9c8e-bc1d2e1941cd.JPG)
![img_1224](https://user-images.githubusercontent.com/26763568/27984648-373ea54c-63d3-11e7-9475-20121c005da8.JPG)

**Comment by tananaev** [comment]
Correct port for Traccar Client is 5055. Why have you changed it?

**Comment by andi968** [comment]
I changed it as 5055 wasn't working either! It is now set back to 5055 and still showing as offline
![img_1224](https://user-images.githubusercontent.com/26763568/27984750-6f9b558c-63d5-11e7-9e1e-02a5a99cc1d0.JPG)
![img_1225](https://user-images.githubusercontent.com/26763568/27984751-6fb984d0-63d5-11e7-8d96-f382304b5f47.PNG)
![img_1226](https://user-images.githubusercontent.com/26763568/27984752-6fba7da4-63d5-11e7-9319-6dc0f9939ebc.PNG)

**Comment by tananaev** [comment]
That's because now port 5055 is closed. Can you please thoroughly check everything yourself before making any further comments.

**Comment by andi968** [comment]
If answers were a bit less cryptic there would be less questions.
So the config for localhost also requires changing to 5055 to use iPad for testing? And revert back for TK110.
Does this mean it needs changing manually  for each protocol ?

**Comment by tananaev** [comment]
Port 8082 is for web interface and Traccar Manager app.

Ports 5xxx are for devices. Specifically 5055 is the port for Traccar Client.

All above is pre-configured by default. I'm not sure why you are trying to change everything.

All this information is also available of the official website and on many forum threads.

**Comment by andi968** [comment]
The reason is two fold.
When I buy an item supplied with software, I like the majority of ppl out here expect it to work more or less out of the box. In this instance this was not the case, with the initial problem of conflicts with my existing pc and the required apps etc I use causing the server to stop running hence try to find a work around. I then installed a clean version of windows on an old laptop to resolve the issue, which has partially worked, I can get the UI up and add devices, the downside is the devices don't communicate with the server even though ports are open.
I have googled, searched the official site and forums and still didn't find a solution, so I ask for help on the forum, believe me, I would rather be doing other things with my time instead of struggling to get this working.

**Comment by tananaev** [comment]
Can you please be more specific on what you've bought exactly?

**Comment by andi968** [comment]
I bought a TK110 bundled with this software.
After a lot of struggling I have now got it working on an old laptop solely as a server, I can now access this remotely from any machine.
The TK110 works on port 5023 fine, the misunderstanding stems from you saying any port can be changed. From passed experience with ipcams all ports had to be the same and I wrongly assumed this would be the same with the trackers.

**Comment by tananaev** [comment]
Traccar is a free software, and we don't sell any hardware. If someone sold it, you probably got scammed.

**Comment by andi968** [comment]
Read the post again, I said it came bundled with the unit, not that I had paid for the software.
I think if anyone is getting scammed, it is you the developer. The software it's self is on par with fox com tracking which I have used for many years. The downside comes when it is bundled with equipment that requires configuration with no support and poor documentation

**Comment by tananaev** [comment]
You haven't bought anything from us and we have no affiliation whatsoever with the vendor that provided you device, allegedly bundled with Traccar software. How can it even be bundled if Traccar is free for everyone?

So, please don't make statements that sound like we owe you something here. I have already provided you some help for free, and it doesn't seem like you appreciated it much.

**Comment by andi968** [comment]
I have never made any statement that you owe me anything, I have even commented how good I think the app is.
When the tracker arrived with the cd with your software on, it was the first I had heard of "Traccar" your attitude is the only downfall with the software, I am grateful for the cryptic and critical advice you have offered for "Free"
I do however take exception to the word "Allegedly" bundled, I would suggest you make a few sample purchases of the low end units and see for yourself and perhaps discuss licensing with the vendors.

**Comment by tananaev** [comment]
Do they really include Traccar on a CD with the device? That's a good advertisement for us, I guess.

**Comment by andi968** [comment]
Only if it works out of the box, I would think they will have  a lot of returns, from my experience selling gps and reversing camera kits years ago.
On a different note, do you know if anyone has successfully ported the server across to work on windows IOT, I am toying with the idea of a micro server just running Traccar

**Comment by tananaev** [comment]
You can run it on any system that support Java, so it might just work using this Java implementation:

http://www.azul.com/downloads/zulu-embedded/

**Comment by andi968** [comment]
I have now run the software on IOS, android and windows successfully for the last two weeks, I am currently using an old aspire one as the server and the other platforms as clients.
After initial setup I have had absolutely seamless tracking, with no crashes no loss of service, I can not find one single fault with the software or apps.
My next plan now after the successful trial period is to use a Raspberry pi3 as a dedicated server and plug in at side of my router and forget about it.
Does anyone know if there is a repository for pi for a simple sudo apt get command ?
A huge thanks to the developers, my Tracker UK subscription expires in a couple of months and will not be getting renewed, thanks to you guys.
A PayPal donation will be heading your way in the next few days.
Kudos guys.

**Comment by tananaev** [comment]
I don't think there is a repository, but you should be able to use regular Linux installer.

**Comment by andi968** [comment]
Thanks for that, I will try that later today and report back.

**Comment by andi968** [comment]
Well that was as easy as pi !
From unpacking my new RPi3 to Traccar up and running took less than an hour!
Here's a short guide to help others
I installed the full version Debian that came supplied with the RPi3
Did the obligatory update.
Install java with 
"sudo apt-get install oracle-java7-jdk"
Downloaded Traccar for Linux and extracted the Traccar.run file to the desktop.
 Then typed in the following in terminal to get into Desktop and press Enter.
cd ~/Desktop
Then typed "sudo chmod +x traccar.run" and press Enter.
Now type "sudo ./Traccar.run" and press Enter, and the installer will run.
Now perform a reboot, open a terminal and type
"$ sudo service traccar status"
You should get the details that service is running.
Open a browser and type
"Localhost8082"
And you will hopefully be presented with the login screen.

Hope the above is helpful to others.

**Comment by andi968** [comment]
After seamless and faultless use over the passed months my device list suddenly cleared, when I try to re add the devices I get the following error as per screen shot attached
![img_1273](https://user-images.githubusercontent.com/26763568/29024160-9ee1f9c2-7b68-11e7-9343-3ffcdf733e38.PNG)

Help please

**Comment by tananaev** [comment]
It means that device with that id is still in the system. You need admin access to link it to your account.

**Comment by andi968** [comment]
Thanks Anton, when I scroll down to Permissions all options are greyed out :-(

**Comment by tananaev** [comment]
It means that you are not admin.

**Comment by andi968** [comment]
I have tried logging in with default admin and admin, and still greyed out.
How do I get round this please
![img_1274](https://user-images.githubusercontent.com/26763568/29024883-0bd0fbf2-7b6c-11e7-83e8-d8c57f336986.JPG)

**Comment by tananaev** [comment]
Looks like someone removed admin privileges from your account. If you don't have another admin user, the only option is to add it directly in the database.

**Comment by tananaev** [comment]
This discussion is completely unrelated to the topic. Please create a separate thread if you want to discuss it further.
