### ISSUE TITLE
Error Mysql Traccar

### ISSUE THREAD

**Issue by josuelmm** [traccar/traccar#4149]
Hi. Good day. Thanks you for the help.
I have a problem con Traccar and Mysql.

I modify the conf file with
```xml
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
    <entry key='database.url'>jdbc:mysql://localhost:3306/dbtraccar?useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>root</entry> 
    <entry key='database.password'>PASS</entry>
```
In the bd, only create two tables (DATABASECHANGELOG, DATABASECHANGELOGLOCK)

This is my wrapper.log.20181125
```
INFO|wrapper|Service traccar|18-11-25 03:05:38|posix_spawn pid 14108
INFO|wrapper|Service traccar|18-11-25 03:05:38|started process 14108
INFO|wrapper|Service traccar|18-11-25 03:05:38|started process with pid 14108
INFO|14108/0|Service traccar|18-11-25 03:05:40|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|14108/0|Service traccar|18-11-25 03:05:43|java.lang.reflect.InvocationTargetException
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at java.lang.reflect.Method.invoke(Method.java:498)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|14108/0|Service traccar|18-11-25 03:05:43|Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at org.traccar.Main.run(Main.java:152)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at org.traccar.Main.main(Main.java:104)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	... 6 more
INFO|14108/0|Service traccar|18-11-25 03:05:43|Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.datatype.DataTypeFactory.fromDescription(DataTypeFactory.java:251)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.change.core.CreateTableChange.generateStatements(CreateTableChange.java:70)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.change.AbstractChange.generateStatementsVolatile(AbstractChange.java:287)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.change.AbstractChange.warn(AbstractChange.java:358)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:109)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:269)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.Liquibase.update(Liquibase.java:198)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.Liquibase.update(Liquibase.java:179)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at liquibase.Liquibase.update(Liquibase.java:175)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:306)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at org.traccar.database.DataManager.<init>(DataManager.java:91)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at org.traccar.Context.init(Context.java:382)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	at org.traccar.Main.run(Main.java:110)
INFO|14108/0|Service traccar|18-11-25 03:05:43|	... 7 more
INFO|wrapper|Service traccar|18-11-25 03:05:43|waitpid 14108 59136
INFO|wrapper|Service traccar|18-11-25 03:05:43|exit code posix process: 59136 application(status/signal): 231/0
```

**Comment by tananaev** [comment]
I suspect that you are using MariaDB. Is that correct?

**Comment by josuelmm** [comment]
> I suspect that you are using MariaDB. Is that correct?

Yes..

**Comment by tananaev** [comment]
That's a known issue that has already been discussed and fixed in the code. Use search.

**Comment by josuelmm** [comment]
I change the connection for 
`    <entry key='database.driver'>org.mariadb.jdbc.Driver</entry>
    <entry key='database.dataSource'>org.mariadb.jdbc.MySQLDataSource</entry>`
and add in wrapper
`wrapper.java.classpath.1=/opt/traccar/lib/mariadb-java-client-2.3.0.jar`
and the same error

**Comment by tananaev** [comment]
It won't help you. As I said, you need to find a thread where it was discussed.

**Comment by josuelmm** [comment]
> It won't help you. As I said, you need to find a thread where it was discussed.
But I'm looking for about what? MariaDB or I still have a problem with mysql

**Comment by tananaev** [comment]
Read this:

https://www.traccar.org/forums/topic/another-40-greater41-problem/
